### ISSUE TITLE
LFS and repo2docker

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercon/2020-zronaghi#2]
Hi @zronaghi !

We were able to run your tutorial after some tweaks to our jupyterhub and kubernetes setup. 

Unfortunately, repo2docker does not support LFS. Would it be possible to change your notebooks so that it downloads the data file e.g. as part of the first cell of the notebook?

For example `wget https://github.com/jupytercon/2020-zronaghi/blob/master/data/data_pop.csv?raw=true -O data_pop.csv`, or from another URL if you have that dataset available elsewhere...

**Comment by SylvainCorlay** [comment]
PS: I did not introduce myself. I am the vicechair of the conference :) this is important for your tutorial to work well on our infrastructure!

Thanks

**Comment by zronaghi** [comment]
Hi @SylvainCorlay ! Thanks for looking into these, sure I can add the URL that you just mentioned above in the intro notebook. Unless there's another place that you recommend we host it.
